spring.application.name=smartclassroom

spring.datasource.url=jdbc:postgresql://localhost:5432/smart_classroom_db
spring.datasource.username=postgres
spring.datasource.password=Vamsi@246

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=10MB

spring.servlet.multipart.max-request-size=10MB
server.port=8080